# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/f/projects/Networking-Tool

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/f/projects/Networking-Tool

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/f/projects/Networking-Tool/CMakeFiles /mnt/f/projects/Networking-Tool//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/f/projects/Networking-Tool/CMakeFiles 0
.PHONY : all

# The main codegen target
codegen: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/f/projects/Networking-Tool/CMakeFiles /mnt/f/projects/Networking-Tool//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 codegen
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/f/projects/Networking-Tool/CMakeFiles 0
.PHONY : codegen

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Networking-Tool

# Build rule for target.
Networking-Tool: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Networking-Tool
.PHONY : Networking-Tool

# fast build rule for target.
Networking-Tool/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Networking-Tool.dir/build.make CMakeFiles/Networking-Tool.dir/build
.PHONY : Networking-Tool/fast

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Networking-Tool.dir/build.make CMakeFiles/Networking-Tool.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Networking-Tool.dir/build.make CMakeFiles/Networking-Tool.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Networking-Tool.dir/build.make CMakeFiles/Networking-Tool.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/room.o: src/room.cpp.o
.PHONY : src/room.o

# target to build an object file
src/room.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Networking-Tool.dir/build.make CMakeFiles/Networking-Tool.dir/src/room.cpp.o
.PHONY : src/room.cpp.o

src/room.i: src/room.cpp.i
.PHONY : src/room.i

# target to preprocess a source file
src/room.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Networking-Tool.dir/build.make CMakeFiles/Networking-Tool.dir/src/room.cpp.i
.PHONY : src/room.cpp.i

src/room.s: src/room.cpp.s
.PHONY : src/room.s

# target to generate assembly for a file
src/room.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Networking-Tool.dir/build.make CMakeFiles/Networking-Tool.dir/src/room.cpp.s
.PHONY : src/room.cpp.s

src/server.o: src/server.cpp.o
.PHONY : src/server.o

# target to build an object file
src/server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Networking-Tool.dir/build.make CMakeFiles/Networking-Tool.dir/src/server.cpp.o
.PHONY : src/server.cpp.o

src/server.i: src/server.cpp.i
.PHONY : src/server.i

# target to preprocess a source file
src/server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Networking-Tool.dir/build.make CMakeFiles/Networking-Tool.dir/src/server.cpp.i
.PHONY : src/server.cpp.i

src/server.s: src/server.cpp.s
.PHONY : src/server.s

# target to generate assembly for a file
src/server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Networking-Tool.dir/build.make CMakeFiles/Networking-Tool.dir/src/server.cpp.s
.PHONY : src/server.cpp.s

src/session.o: src/session.cpp.o
.PHONY : src/session.o

# target to build an object file
src/session.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Networking-Tool.dir/build.make CMakeFiles/Networking-Tool.dir/src/session.cpp.o
.PHONY : src/session.cpp.o

src/session.i: src/session.cpp.i
.PHONY : src/session.i

# target to preprocess a source file
src/session.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Networking-Tool.dir/build.make CMakeFiles/Networking-Tool.dir/src/session.cpp.i
.PHONY : src/session.cpp.i

src/session.s: src/session.cpp.s
.PHONY : src/session.s

# target to generate assembly for a file
src/session.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Networking-Tool.dir/build.make CMakeFiles/Networking-Tool.dir/src/session.cpp.s
.PHONY : src/session.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... codegen"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Networking-Tool"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/room.o"
	@echo "... src/room.i"
	@echo "... src/room.s"
	@echo "... src/server.o"
	@echo "... src/server.i"
	@echo "... src/server.s"
	@echo "... src/session.o"
	@echo "... src/session.i"
	@echo "... src/session.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

